### ISSUE TITLE
Planetarium chance

### ISSUE THREAD

**Issue by jammybagel** [Sectimus/isaac-planetarium-chance#1]
Once entering a planetarium (unsure of if it is the same if seen but unentered) the planetarium chance should drop to 0% for the remainder of the run unless holding telescopic lens however it does not do so unless you reach chapter 4 not tested whether telescopic lens puts the chance back to 15% as it should once a planetarium has been found however will update you on this

**Comment by Sectimus** [comment]
This already exists, however it will not show until you reach the next floor.
```lua
if self.storage.visited then
    self.storage.currentFloorSpawnChance = 1
    if Isaac.GetPlayer():HasTrinket(TrinketType.TRINKET_TELESCOPE_LENS) then
        --If Isaac enters a Planetarium, the chance will be set to 1% and can be increased only with a Telescope Lens, by 15%.
        self.storage.currentFloorSpawnChance = 15
    end
end
```

**Comment by Sectimus** [comment]
Ah, upon reading that again I can see the confusion, the [wiki](https://bindingofisaacrebirth.fandom.com/wiki/Planetarium) says "If Isaac enters a Planetarium, the chance will be set to 1% and can be increased only with a Telescope Lens, by 15%."
