### ISSUE TITLE
Bug?: "GetShaderParams" failed

### ISSUE THREAD

**Issue by XDarin** [Sectimus/isaac-planetarium-chance#11]
The mod doesn't work. It's enabled, but it doesn't show the planetarium chance at all. It also spams messages in console: 
"GetShaderParams" failed: ...Isaac Repentance v4.0.4/mods/planetarium chance/main.lua:156: attempt to call a nil value (method 'IsAscent'
![console-screenshot](https://user-images.githubusercontent.com/92124171/142239002-3b09f549-f994-447e-b906-6a0bf2aa50d9.png)
)
happens on any character

**Comment by kittenchilly** [comment]
Try updating to the latest Isaac version. It's checking for a function that got added in an update.
