### ISSUE TITLE
The icon doesn't behave like the other parts of the HUD when going into the pause menu

### ISSUE THREAD

**Issue by InfamouslyJaded** [Sectimus/isaac-planetarium-chance#15]
![image](https://user-images.githubusercontent.com/79400302/148639088-87390c3d-37ea-4ca6-b370-4ba082c2f3d2.png)
They either get darker, more transparent or both, not sure which exactly, but the planitarium chance stands out.

**Comment by kittenchilly** [comment]
This is a limitation with the API. Just going to have to deal with it for now.
