### ISSUE TITLE
planetarium chance is not working

### ISSUE THREAD

**Issue by RadiatoMan** [Sectimus/isaac-planetarium-chance#5]
when i start a new game this appears in the console : 
"PostGameStart" failed: resources/scripts/json.lua:125: Unterminated JSON encoded object found at position in [ ]
what can i do to fix it??, i tried deactivating all my mods, also tried uninstalling and installing the planetarium chance mod but it doesnt work.

**Comment by Sectimus** [comment]
Could you take a screenprint of your console and upload it here when the error occurs? Have you tried [this fix](https://steamcommunity.com/workshop/filedetails/discussion/2489006943/3104647961271242130/)?

**Comment by RadiatoMan** [comment]
thanks, that fix helped its working again :D
